name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # or your default branch

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the code
      - name: Checkout source code
        uses: actions/checkout@v3

      # 2. Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'  # or your preferred version

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run tests
      - name: Run Tests
        run: |
          # Replace the following line with your actual test command (e.g., pytest)
          echo "Running tests..."

      # 5. Deploy to EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}        # e.g., your EC2 public IP
          username: ${{ secrets.EC2_USER }}      # e.g., "ubuntu"
          key: ${{ secrets.EC2_SSH_KEY }}        # Your EC2 private key (store this as a secret)
          port: 22                             # SSH port (typically 22)
          script: |
            cd /home/ubuntu/phase_2_imdb      # Adjust the path on your EC2 instance if needed
            git pull origin main             # Update the repo with the latest changes
            pkill -f "python3 app.py" || true # Kill any running instance of your app
            nohup python3 app.py > app.log 2>&1 &  # Restart your app in the background
