name: CI/CD Pipeline

on:
  push:
    branches: [ main ]  # Adjust if needed

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: phase_3_imdb
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgpgme-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          # Replace with your actual test command, for example: pytest
          echo "Running tests..."

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}        # The public IP or DNS of your EC2 instance
          username: ${{ secrets.EC2_USER }}      # Typically "ec2-user" (or "ubuntu" for Ubuntu)
          key: ${{ secrets.EC2_SSH_KEY }}        # Your private PEM key contents
          port: 22                             # SSH port
          script: |
            cd /home/ec2-user/your-project      # Adjust to the correct directory on your EC2 instance
            git pull origin main
            pkill -f "python3 app.py" || true
            nohup python3 app.py > app.log 2>&1 &
