name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: phase_3_imdb

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install OS dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgpgme-dev libgpg-error-dev pkg-config
          which gpgme-config || true
          gpgme-config --version || true

      - name: Stub gpgme-config if not found
        run: |
          if ! command -v gpgme-config >/dev/null; then
            sudo tee /usr/local/bin/gpgme-config > /dev/null << 'EOF'
    #!/bin/bash
    if [ "$1" = "--version" ]; then
      echo "1.18.0"
    elif [ "$1" = "--cflags" ]; then
      echo "-I/usr/include/gpgme"
    elif [ "$1" = "--libs" ]; then
      echo "-lgpgme"
    else
      echo ""
    fi
    EOF
            sudo chmod +x /usr/local/bin/gpgme-config
          fi
          echo "Using gpgme-config at: $(which gpgme-config)"
          gpgme-config --version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: |
          # Replace with your actual test command, e.g., pytest
          echo "Running tests..."

      - name: Deploy & restart Flask app
        uses: appleboy/ssh-action@v0.1.10
        with:
          host:        ${{ secrets.EC2_HOST }}
          username:    ${{ secrets.EC2_USER }}
          key:         ${{ secrets.EC2_SSH_KEY }}
          port:        22
          timeout:     120s
          script_stop: false
          script: |
            set -eu
            # Ensure tmux & git are installed
            sudo yum install -y tmux git || sudo apt-get install -y tmux git

            REPO_ROOT=~/imdb-lorentz/phase_3_imdb
            if [ -d "$REPO_ROOT" ]; then
              cd "$REPO_ROOT" && git pull origin main
            else
              git clone https://github.com/${{ github.repository }}.git ~/imdb-lorentz
              cd "$REPO_ROOT"
            fi

            # Install Python dependencies on the EC2 host
            pip3 install --user -r requirements.txt

            # Restart Flask in tmux
            tmux kill-session -t flask || true
            tmux new-session -d -s flask "FLASK_ENV=production python3 app.py"

            exit 0
